name: GoSec Diff-Aware Scan

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read

jobs:
  gosec-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Fetch main branch
        run: git fetch origin main

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install GoSec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      # --- Baseline Scan on main ---
      - name: Checkout main branch
        run: |
          git checkout origin/main
          mkdir baseline
          cp -r * baseline/ || true

      - name: Run GoSec on main (baseline)
        run: |
          cd baseline
          gosec -no-fail -fmt=json -out ../baseline-results.json ./...

      # --- Restore PR branch ---
      - name: Checkout PR branch again
        run: git checkout ${{ github.head_ref }}

      # --- Find changed Go files ---
      - name: Get changed Go files
        id: changes
        run: |
          CHANGED=$(git diff --name-only origin/main...HEAD | grep '\.go$' || true)
          echo "Changed files: $CHANGED"
          echo "files=$CHANGED" >> $GITHUB_OUTPUT

      # --- Run GoSec on changed files only ---
      - name: Run GoSec on changed files
        if: steps.changes.outputs.files != ''
        run: |
          FILES="${{ steps.changes.outputs.files }}"
          echo "Scanning changed files: $FILES"
          gosec -no-fail -fmt=json -out changed-results.json $FILES

      # --- Comment on PR with changed files results ---
      - name: Comment PR with findings
        if: steps.changes.outputs.files != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COUNT=$(jq '.Issues | length' changed-results.json)
          if [ "$COUNT" -eq 0 ]; then
            COMMENT="✅ No GoSec issues found in changed files."
          else
            COMMENT="⚠️ *GoSec found $COUNT high-severity issue(s) in changed files:*\n\n\`\`\`json\n$(jq '.' changed-results.json)\n\`\`\`"
          fi
          echo -e "$COMMENT" > comment.txt
          gh pr comment ${{ github.event.pull_request.number }} --body-file comment.txt
