name: GoSec Diff-Aware Scan

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write  # Needed to comment on PR
  contents: read

jobs:
  gosec-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Fetch base branch for comparison
        run: |
          git fetch origin main

      # --- Baseline Scan (Main Branch) ---
      - name: Checkout main branch
        run: |
          git checkout origin/main
          mkdir baseline
          cp -r * baseline/ || true

      - name: Run GoSec on Main (Baseline)
        run: |
          cd baseline
          gosec -severity high -no-fail -fmt=json -out ../baseline-results.json ./...

      # --- Restore PR branch for Diff Scan ---
      - name: Checkout PR branch again
        run: |
          git checkout -
        
      # --- Changed Files Scan ---
      - name: Get changed Go files
        id: changes
        run: |
          CHANGED=$(git diff --name-only origin/main...HEAD | grep '\.go$' || true)
          echo "Changed files: $CHANGED"
          echo "files=$CHANGED" >> $GITHUB_OUTPUT

      - name: Run GoSec on changed files only
        if: steps.changes.outputs.files != ''
        run: |
          FILES="${{ steps.changes.outputs.files }}"
          echo "Scanning changed files: $FILES"
          gosec -severity high -no-fail -fmt=json -out changed-results.json $FILES

      # --- PR Comment with Changed File Findings ---
      - name: Comment PR with findings
        if: steps.changes.outputs.files != ''
        run: |
          COUNT=$(jq '.Issues | length' changed-results.json)
          if [ "$COUNT" -eq 0 ]; then
            echo "No issues found in changed files."
            COMMENT="✅ No GoSec issues found in changed files."
          else
            echo "Found $COUNT issue(s)."
            COMMENT="⚠️ *GoSec found $COUNT high-severity issue(s) in changed files:*\n\n\`\`\`json\n$(jq '.' changed-results.json)\n\`\`\`"
          fi
          COMMENT_FILE=comment.txt
          echo -e "$COMMENT" > $COMMENT_FILE
          gh pr comment ${{ github.event.pull_request.number }} --body-file $COMMENT_FILE
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh
